export const ROLES = {
  ADMIN: 'ADMIN',
  TECHNICIAN: 'TECHNICIAN',
  REQUESTER: 'REQUESTER',
} as const;

export const TICKET_STATUS = {
  OPEN: 'OPEN',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  ON_HOLD: 'ON_HOLD',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
} as const;

export const AUDIT_ACTIONS = {
  TICKET_CREATED: 'TICKET_CREATED',
  STATUS_CHANGE: 'STATUS_CHANGE',
  PRIORITY_CHANGE: 'PRIORITY_CHANGE',
  ASSIGNMENT: 'ASSIGNMENT',
} as const;

export const JWT_EXPIRATION = '8h';
